apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-influx-deployment
  namespace: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-influx
  template:
    metadata:
      labels:
        app: mqtt-influx
    spec:
      containers:
      - name: mqtt-influx
        image: noyusu/mqtt-influx-image:v0.0.4
        ports:
        - containerPort: 1883

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-influx-service
  namespace: telegraf
spec:
  type: ClusterIP
  ports:
  - port: 1883
    targetPort: 1883
  selector:
    app: mqtt-influx
